# SonarQube Server URL
sonar.host.url=http://13.53.35.224:9000

# Project Key and Name

sonar.projectKey=My_sample_Project
sonar.projectName=My_sample_Project
sonar.projectVersion=1.0

# Source and Test Files
sonar.sources=src
sonar.tests=test

# Language and Encoding
sonar.language=java
sonar.sourceEncoding=UTF-8

# Binaries and Libraries
sonar.java.binaries=target/classes
sonar.java.libraries=target/lib/*.jar

# Coverage Reports (for JaCoCo)
sonar.junit.reportsPath=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec

# Exclusions (if needed)
sonar.exclusions=**/*.xml, **/*.json

# Log Level (Optional)
sonar.log.level=INFO
